---
title: "Noisy Kids Replication Analysis"
author: "Dan Yurovsky"
date: "August 03, 2015"
output:
  html_document:
    highlight: tango
    theme: spacelab
---
```{r setup, include=FALSE}
library(knitr)
opts_chunk$set(message=FALSE, warning=FALSE, cache=FALSE)
```

Load libraries
```{r, cache = FALSE}
library(dplyr)
library(langcog)
library(tidyr)
library(magrittr)
library(lme4)
library(lmerTest)
library(jsonlite)
library(dplyr)
library(tidyr)
library(ggplot2)
library(readr)
library(jsonlite)

na.mean <- function(x){mean(x, na.rm = TRUE)}
```


Load child data
```{r load_child_data, cache=FALSE}
#######################################################################
############################ LOADING FILES ############################
#######################################################################
# grab all file names from data dir
child.files <- list.files(path = "experiment_nicolette/data/", 
                            pattern = 'results_*', all.files = FALSE)

child.demos <- read_csv('experiment_nicolette/data/noisy_replication_demos.csv') %>%
  filter(Data==TRUE)

child.overwrite <- read_csv('experiment_nicolette/data/overwrite.csv')

# function for reading one child's data
read.child <- function(filename) {
  #read raw data and break up by html lists
  data <- readLines(paste0("experiment_nicolette/data/",filename),warn=FALSE)
  data <- unlist(strsplit(data,'<li>'))
  data<- data[3:194]
  
  # clean up the data, getting rid of html escape characters, etc.
  data <- gsub("\\\\\"","",data)
  data <- gsub("</li>","",data)
  data <- gsub("</ul>\\},\\{<ul>","",data)
  data <- gsub("\"","",data)
  data <- gsub("</ul>}]</ul>}","",data)
  data <- gsub("{<ul>","",data,fixed=TRUE)
    
  # munge
  split.data <- strsplit(data,": ")
  split.frame <- data.frame(t(sapply(split.data,unlist)))
  names(split.frame) <- c("measure", "value")
  split.frame$subj <- filename
  split.frame$trial <- sort(rep(1:16,12))
  split.frame$order = split.frame$value[2]
return(split.frame)
}  

code.literal <- function(value,trial.type,condition) {
  
  literal = rep(0,length(value))
  
  literal[trial.type == "Training" & value == "Y"] <- 1
  literal[condition == "Control" & value == "Y"] <- 1
  literal[condition != "Control" & trial.type == "Test" & value != "Y"] <- 1
  
  return(literal)
}


child.long.data <- bind_rows(lapply(child.files,read.child)) %>%
  filter(measure %in% c("word", "response")) %>%
  spread(measure,value) %>%
  rowwise() %>%
  mutate(condition = if(order == "0") "Normal"
         else if(order == "1") "Implausible"
         else if(order == "2") "Control"
         else if(order == "3") "No Noise Normal"
         else "No Noise Implausible") 

child.demos$subj = unique(child.long.data$subj)

child.overwrite.data <- left_join(child.long.data,child.demos)

for(row in nrow(child.overwrite)) {
  child.overwrite.data[child.overwrite.data$subj == child.overwrite[row,]$subj &
                         child.overwrite.data$trial == child.overwrite[row,]$trial,
                       ]$response = child.overwrite[row,]$response
}

child.overwrite.data %<>%
  ungroup() %>%
  mutate(condition = factor(condition,
                            levels = c("Normal", "Implausible", 
                                       "Control", "No Noise Normal",
                                       "No Noise Implausible")),
         trial.type = factor(ifelse(trial <= 8, "Training", "Test"))) %>%
  filter(age >= 4, age <= 6, Exclude == FALSE) %>%
  mutate(Literal = code.literal(response,trial.type,condition)) %>%
  mutate(experiment = "replication") %>%
  select(experiment,subj,age,condition,trial.type,word,Literal)
```

Load original child data
```{r,cache=FALSE}
original.child.data <- read.csv('sarah_honors_data_updated_5-11.csv')

original.child.long.data <- gather(original.child.data,item,
                                   response,cat_kittens:pen) %>%
  rename(condition = cond, subj = subj_id) %>%
  mutate(condition = factor(condition,levels=c("normal","implausible"),
                            labels = c("Normal", "Implausible"))) %>%
  group_by(condition,item,subj) %>%
  mutate(trial.type = ifelse(item %in% c("cat_kittens","book_table","shark_fish",
                                         "wooden_blocks", "flowers_basket",
                                         "house_door","bread_peanutbutter",
                                         "knife_fork"), 
                             "Training", "Test")) %>%
  rowwise() %>%
  mutate(Literal = ifelse(trial.type == "Training", 1 - response, response)) %>% 
  filter(age >= 4, age <= 6, item != "avg_correct") %>%
  mutate(experiment = "original") %>%
  ungroup() %>%
  rename(word = item) %>%
  select(experiment, subj, age, condition,trial.type, word, Literal) 

all.child.long.data <- bind_rows(child.overwrite.data,original.child.long.data) %>%
  group_by(experiment,condition, trial.type) %>%
  ungroup() %>%
  mutate(trial.type = factor(trial.type, levels = c("Training", "Test"))) %>%
  group_by(experiment,condition,trial.type)
```

Load Adult data
```{r,cache=FALSE}
all.adult.files <- paste0("adult_data/",
                          list.files(path = "adult_data/", pattern = '*.json', 
                                     all.files = FALSE))
jsons <- lapply(all.adult.files,fromJSON)
workers <- sapply(jsons,function(x) x$WorkerId)
adult.data <- bind_rows(sapply(jsons,function(x) x$answers$data,simplify=FALSE))

adult.data$worker <- unlist(lapply(workers, function (x) rep(x,15)))
```

Munge adult data
```{r}
#Exclude multiple hits from a single participant
firstHits <- adult.data %>%
  group_by(worker) %>%
  summarise(timeStamp = min(timestamp))

adult.long.data <- inner_join(adult.data,firstHits) %>%
  ungroup() %>%
  rename(condition = order, subj = worker) %>%
  mutate(response = ifelse(response == "Y",TRUE,FALSE),
         condition = ifelse(condition == 0,"Normal","Implausible"),
         trial.type = ifelse(trialnum > 8, "Test", "Training"),
         experiment = "adult", age = NA) %>%
  mutate(condition = factor(condition,levels = c("Normal", "Implausible"))) %>%
  rename(Literal = response) %>%
  select(experiment, subj, age, condition, trial.type, word, Literal)
```


Model data
```{r models}
new.child.data <- child.overwrite.data %>%
  rowwise() %>%
  mutate(ambig.type = if(trial.type == "Training") as.character(NA)
         else if(word %in% c("shirt_die", "carrots_bees", "fan_airport", 
                             "coats_horses", "carrots_bees", "van_airport", 
                             "goats_horses", "shirt_tie")) "consonant"
         else "vowel") %>%
  ungroup() %>%
  mutate(speaker.type = ifelse(condition %in% c("Normal", "Normal No Noise"),
                               "Plausible", "Implausible"),
         noise.type = ifelse(condition %in% c("Normal", "Implausible", "Control"),
                             "Noisy", "No Noise"),
         test.type = ifelse(condition == "Control", "Control", "Ambiguous")) %>%
  mutate(noise.type = factor(noise.type, levels = c("Noisy", "No Noise")))

lm.child.v1 <- glmer(Literal ~ speaker.type + noise.type + test.type + (1|age) + 
                       (1|word) + (1|subj),
                  family = "binomial", data = filter(new.child.data,trial.type == "Test"))

summary(lm.child.v1)

lm.child.v2 <- glmer(Literal ~ condition  +  (1|age) + (1|word) + (1|subj),
                  family = "binomial", data = filter(new.child.data,trial.type == "Test"))

summary(lm.child.v2)

```


Analyze child data
```{r child_analysis}
all.long.data <- bind_rows(all.child.long.data,adult.long.data) %>%
  mutate(trial.type = factor(trial.type, levels = c("Training", "Test"))) %>%
  mutate(condition = factor(condition, levels = c("Control", "Normal", 
                                                  "Implausible", "No Noise Normal",
                                                  "No Noise Implausible"))) %>%
  group_by(experiment, condition, trial.type)

ns <- all.long.data %>% 
  ungroup() %>% 
  select(experiment,trial.type,condition,subj) %>% 
  distinct() %>% 
  group_by(experiment,condition, trial.type) %>% 
  summarise(n = n())

kable(filter(ns, trial.type == "Test"))

all.results <- multi_boot_standard(all.long.data, column = "Literal") %>%
  left_join(ns) %>%
  ungroup() %>%
  mutate(condition = factor(condition, levels = c("Control", "Normal", 
                                                  "No Noise Normal", "Implausible",
                                                  "No Noise Implausible"),
                             labels = c("Control", "Normal","No Noise\nNormal",
                                                  "Implausible", 
                                        "No Noise\nImplausible")))
```

Plot Separately
```{r child_plot,fig.height=5,fig.width=9, cache = FALSE}
new.child.results <- filter(all.results,experiment == "replication", trial.type == "Test")

exp1.results <- filter(new.child.results, condition %in% c("Normal", "Implausible"))

#quartz(width = 5, height = 4)
ggplot(exp1.results, aes(x=condition, y=mean, fill=trial.type)) +
  geom_bar(stat="identity",position=position_dodge(1))+
  geom_linerange(aes(ymin = ci_lower,
                      ymax = ci_upper),
                  size = .8,
                  show_guide = FALSE,
                 position=position_dodge(1)) +
  scale_fill_brewer(palette="Set1") +
  geom_hline(aes(yintercept=.5),lty=2)+
  theme_bw(base_size=14) +
  theme(legend.position="none", panel.grid=element_blank()) +
  scale_x_discrete(name = "Speaker Type")+
  scale_y_continuous(name = "Proportion Choosing Plausible",
                     limits=c(0,1))

exp2.results <- filter(new.child.results, condition %in% c("Control", "Normal", 
                                                           "Implausible"))

#quartz(width = 6, height = 4)
ggplot(exp2.results, aes(x=condition, y=mean, fill=trial.type)) +
  geom_bar(stat="identity",position=position_dodge(1))+
  geom_linerange(aes(ymin = ci_lower,
                      ymax = ci_upper),
                  size = .8,
                  show_guide = FALSE,
                 position=position_dodge(1)) +
  scale_fill_brewer(palette="Set1") +
  geom_hline(aes(yintercept=.5),lty=2)+
  theme_bw(base_size=14) +
  theme(legend.position="none", panel.grid=element_blank()) +
  scale_x_discrete(name = "Speaker Type")+
  scale_y_continuous(name = "Proportion Choosing Plausible",
                     limits=c(0,1))


exp3.results <- filter(new.child.results, condition %in% c("Control", "Normal", 
                                                           "Implausible", "No Noise\nNormal"))


#quartz(width = 7, height = 4)
ggplot(exp3.results, aes(x=condition, y=mean, fill=trial.type)) +
  geom_bar(stat="identity",position=position_dodge(1))+
  geom_linerange(aes(ymin = ci_lower,
                      ymax = ci_upper),
                  size = .8,
                  show_guide = FALSE,
                 position=position_dodge(1)) +
  scale_fill_brewer(palette="Set1") +
  geom_hline(aes(yintercept=.5),lty=2)+
  theme_bw(base_size=14) +
  theme(legend.position="none", panel.grid=element_blank()) +
  scale_x_discrete(name = "Speaker Type")+
  scale_y_continuous(name = "Proportion Choosing Plausible",
                     limits=c(0,1))
```


Plot Together
```{r child_plot,fig.height=5,fig.width=9, cache = FALSE}
ggplot(all.results, aes(x=condition, y=mean, fill=trial.type)) +
  geom_bar(stat="identity",position=position_dodge(1))+
  facet_grid(experiment ~ trial.type) +
  geom_linerange(aes(ymin = ci_lower,
                      ymax = ci_upper),
                  size = .8,
                  show_guide = FALSE,
                 position=position_dodge(1)) +
  scale_fill_brewer(palette="Set1") +
  geom_hline(aes(yintercept=.5),lty=2)+
  theme_bw(base_size=14) +
  theme(legend.position="none", panel.grid=element_blank()) +
  scale_x_discrete(name = "Condition")+
  scale_y_continuous(name = "Proportion choosing Literal",
                     limits=c(0,1))
```